sudo: required

language: python
python:
  - 3.6

env:
  global:
    secure: "xjqC3Q4FKYpitbBRNbNKiPaRv7XE63OCGDvzJbuX2IS0VwEsNaTjzzjun2orOQr5ATuUI2s4xZQpQFnCpay5wGU5vfRa0bZ78FyF9SVTrI0wRAhlKkLIyMLEf6O/HYBfC4ou3PIHeAgEYH4uAekmu4+9NjwbEWA/9dcnCXQEht3ypB12KGgFoVvvRo0hEqfpjEaDhufU1naUg/IeN61vxBRtG3nVgZTrDM/FnmLI4AgCGJe7t0UAa8/CEPBIeHoDsiKF0lPWCJfYve8VyLIaZJ7JKcPiPTtiqOTA9Ivm9ptvWWyWwc2htYmGMWWEEUFXAXm1+B3WBpmShzTg/m2WEU8gMtQU6AP1gMLB5NwcrWV9XWTkPVNYtonARkKYxv6xJ6xMmJE4qz6pklODxKS3A1cKHLAFIqG36nFbpGjsbH4PczqQrd3QeVnJ+NCVdFSFqRjwa7Kiuvzq6uynwM6/+Tjcj/T01W4fk/v7VsDrr08hGXqjHeH/jBweslra3OQR6bz9j0HeYm4XCck/Oav4q2TXlCknB5rZfVVncBO4ao1CReFpPQmS2qsKybhtm8ADnoVtLltTQGuilCx5hjC0ZZ7nRdLG1ZvRm91Hi/CeKuGbQSZAQ3z9NErD9a9QSCRty2sHGIZcLOoxL6PTtRGO1A3DPhiF3Sx4uvUvhDJgebI="
    secure: "Ync8hXhMF6/3z+UKHg2Ha1MVywmVcyUkx9Md+xOElg/kNziF8Jyam3/rcfK02qrV8KPVAkuGbWo1UPANViY3MVmD0A0HdrKvsikxb5CN+m6sE7dR5k3uY02nCkmgV+M0LY2MM3fvzPtIwkODGwC6lNpZZs4l/ziKZFirwmYaLYfyjnwRWL4vT2bjIH3+NUTYcr7tvDVGoPOZPT/5Ge8UFH0hcpEGl5N7Ofc65ooppLj57yFvXdQYgBUGkCOdXcB+qRAqXcOAe1sLRmQhFzkQc/tryoAppM4vfsdlGsVjhSusLtv1okJ8Og62T1tRdsbueolU+hebceS+Uk+vUkUWRvl+iWVCDprErftSiyieYc18N0hD1pdlP1vkai/YFHmKto1n5iZSRth9L9G0uPkbk6/cBnRHWLkre3pOMv20d1kAuVFcMKfh6OWVAe+zg8vp4j3YRs0EK6SCXjPsdnwdXxsJZSCRNeYBlEJHYLCHU0NOZ+2o+DOT3F+O6OQrWN/+5sTc8wneNffmNDYYZ5nDDwCAOaZPtuBBd81kxk3MmrpDvXSewdfxoEDyliYbfgv3YtOYAq0nBgpOGATlbyKrJh/eE4Odu4EL8mUUL2uIWv/+dxLziSjvmQ+yXpK4zkvh+cqqHmVdcnm4vSp1Souu+CDLnYjoUc6zIoXctjroi1U="

services:
  - docker

script:
  - bash production.sh
  - bash development.sh

#custom deployment
after_success:
  - eval "$(ssh-agent -s)" #start the ssh agent
  - ssh fg@146.185.181.250
  - bash test.sh