language: python
python:
  - 3.6

services:
  - docker

install:
  - docker build -t django ./src/django_backend/
  - docker run -d -p 127.0.0.1:80:80 --name django django

script:
  - docker ps | grep -q django
  # Run tests in django application from here