sudo: required

language: python
python:
  - 3.6

services:
  - docker

addons:
  ssh_known_hosts: 146.185.181.250 # Our staging server is located here

before_script:
  - bash development.sh

script:
  - docker exec -it django ./manage.py test # Runs the django tests

# This sets up the ssh key for travis, the deploy_rsa.enc is encrypted and can safely be stored on the git repo
before_deploy:
  - openssl aes-256-cbc -K $encrypted_f56fe3551327_key -iv $encrypted_f56fe3551327_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

# This script is run by the travis CI machine given all previous steps are successful
deploy:
  provider: script
  skip_cleanup: true
  script: bash $TRAVIS_BUILD_DIR/deploy_staging.sh
  on:
    branch: development