sudo: required

env:
  DOCKER_COMPOSE_VERSION: 1.11

before_install:
  - sudo apt-get update
  - sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-engine
  - docker-compose -v
  