sudo: required
language: node_js
node_js:
  - 8
services:
  - docker

cache:
  directories:
    - src/angular_frontend/node_modules

addons:
  ssh_known_hosts: 146.185.181.250 # Our staging server is located here

jobs:
  include:
    - stage: test django
      env:
        - DOCKER_COMPOSE_VERSION=1.14.0
      install:
        - docker -v
        - sudo rm /usr/local/bin/docker-compose
        - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
        - chmod +x docker-compose
        - sudo mv docker-compose /usr/local/bin
        - bash travis.sh
      script:
        - docker exec -i django bash remove-migrations.sh
        - docker exec -i django python manage.py makemigrations
        - docker exec -i django python manage.py test

    - stage: test angular
      install:
        - npm install -g @angular/cli@1.4.2
        - export CHROME_BIN=/usr/bin/google-chrome
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
        - sudo apt-get update
        - sudo apt-get install -y libappindicator1 fonts-liberation
        - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        - sudo dpkg -i google-chrome*.deb
        - cd src/angular_frontend && npm install
      script:
        - ng lint
        - ng build --prod
        #- ng test --watch=false

    - stage: deploy
      script: echo "Deploying to staging..."
      before_deploy:
        - openssl aes-256-cbc -K $encrypted_f56fe3551327_key -iv $encrypted_f56fe3551327_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
        - eval "$(ssh-agent -s)"
        - chmod 600 /tmp/deploy_rsa
        - ssh-add /tmp/deploy_rsa
      deploy:
        provider: script
        skip_cleanup: true
        script:
            - ssh fg@fgbeta.samfundet.no 'bash -s' < $TRAVIS_BUILD_DIR/deploy_staging.sh
            - rsync -r $TRAVIS_BUILD_DIR/src/angular_frontend/dist fg@146.185.181.250:./fg/src/angular_frontend/
        on:
          branch: development
