version: '2'

services:
  angular:
    build: ./src/angular_frontend
    container_name: angular
    volumes:
      - ./src/angular_frontend:/home/app/angular

  nginx:
    restart: always
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - webserver_network
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./src/angular_frontend:/static/angular
      - ./src/django_backend:/django

  django:
    restart: always
    build: ./src/django_backend
    container_name: django
    expose:
      - "8000"
    networks:
      - webserver_network
      - database_network
    volumes:
      - ./src/django_backend:/django

  postgres:
    restart: "no"
    image: postgres:latest
    container_name: postgres
    networks:
      - database_network
    volumes:
      - ./db_data:/var/lib/postgresql/data

networks:
  webserver_network:
    driver: bridge
  database_network:
    driver: bridge
