version: '2'

services:
  angular:
    build: ./src/angular_frontend
    container_name: angular
    volumes:
      - ./src:/home/app
      - /home/app/angular_frontend/node_modules

  nginx:
    restart: always
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - webserver_network
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./src/angular_frontend:/static/angular
      - ./src/django_backend:/django

  django:
    restart: always
    build: ./src/django_backend
    container_name: django
    expose:
      - "8000"
    networks:
      - webserver_network
      - database_network
    volumes:
      - ./src/django_backend:/django
    depends_on:
      - postgres

  postgres:
    restart: always
    image: postgres:9.6.2
    container_name: postgres
    networks:
      - database_network
    volumes:
      - ./postgres/data:/var/lib/postgresql/data/pgdata


networks:
  webserver_network:
    driver: bridge
  database_network:
    driver: bridge
