version: '3'

services:
  nginx:
    restart: always
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - webserver_network
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./src/angular_frontend:/static/angular:ro # read only: ro
      - ./src/django_backend:/django

  django:
    restart: always
    build: ./src/django_backend
    container_name: django
    expose:
      - "5069"
    networks:
      - webserver_network
      - database_network
    volumes:
      - ./src/django_backend:/django
    depends_on:
      - postgres

  postgres:
    restart: always
    image: postgres:9.6.2
    container_name: postgres
    networks:
      - database_network
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  angular:
      restart: always
      #image: nikzy/fg_frontend:1.0
      build: src/angular_frontend
      container_name: angular
      networks:
          - webserver_network
          - database_network
      expose:
          - "4200"
      volumes:
          - ./src/angular_frontend/:/src/

volumes:
  django_volume:
  static_volume:
  postgres_volume:

networks:
  webserver_network:
    driver: bridge
  database_network:
    driver: bridge
